### PR TITLE
Fix: Video captions on Part1 set1 page do not show what videos are about.

### PR DESCRIPTION
**Pull request by Dkingofcode**
**This pull request makes the following changes:**
* Fixes issue #55 

**Checklist:**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me
- [x] I certify that I ran my checklist.

Ping @Ifycode/git-github-training-resource

### CODE REVIEW

**Comment by Dkingofcode** [comment]
@Ifycode  fix: Video captions on Part 1 set 1 page do not show what videos are about.
- #55

**Comment by Dkingofcode** [comment]
@Ifycode  Finished making the changes 
- #55

**Comment by Ifycode** [comment]
#### 1. About pull request title 
@Dkingofcode the instruction on that page I sent you talked about your pull request title. Instead you created a new comment. Delete this comment you wrote - https://github.com/Ifycode/git-github-training-resource/pull/58#ISSUECOMMENT-1279809068, and then do the right thing to your pull request title. 

#### 2. About linking your issue to pull request
In the other comment where you told me that you have finished making your changes - https://github.com/Ifycode/git-github-training-resource/pull/58#issuecomment-1279809541, remove the link to the issue from there and do it in the right place where there is already a template - https://github.com/Ifycode/git-github-training-resource/pull/58#issue-1410260405

**Review by Ifycode — APPROVED** [review]
Nicely done 👍

**Pull request merged**
